### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by reddyse** [reddyse/webtools#6]
2.Security-
-http://alvinalexander.com/blog/post/jsp/how-test-valid-user-session-jsp
-http://www.mkyong.com/spring-security/spring-security-hello-world-example/

**Comment by ankurbag** [comment]
Not able to read artifact
http://stackoverflow.com/questions/6642146/maven-failed-to-read-artifact-descriptor

**Comment by ankurbag** [comment]
Customized Url pattern:
http://stackoverflow.com/questions/23705846/security-constraint-url-pattern-and-the-character-within-web-xml

**Comment by ankurbag** [comment]
http://www.mkyong.com/spring-security/spring-security-form-login-example/
